binop_separator = "Back"
brace_style = "PreferSameLine"
edition = "2018"
hard_tabs = true
max_width = 99
overflow_delimited_expr = true
use_field_init_shorthand = true
#use_small_heuristics = "Max"
version = "Two"
where_single_line = true
